   //Data
   
   const proposals = {
      ux: [
        {
          id: 1,
          name: 'Julian Henderson',
          initials: 'JH',
          color: 'from-sky-400 to-blue-600',
          rating: 4.9,
          reviews: 120,
          success: '98%',
          badge: null,
          bid: '$1,200',
          preview: 'I have over 8 years of experience designing complex financial interfaces. My approach focuses on simplifying dense data into actionable insights for end-users while maintaining bank-grade trust…',
          location: 'New York, USA',
          skills: ['UI/UX Design', 'Figma', 'FinTech', 'Design Systems', 'Prototyping'],
          bio: 'Senior product designer with a focus on financial technology and data-heavy dashboards. I\'ve shipped design systems for 3 Series B startups and love turning complexity into clarity.',
          hourly: '$95/hr',
          completed: 47,
        },
        {
          id: 2,
          name: 'Sarah Al-Mansour',
          initials: 'SA',
          color: 'from-violet-400 to-purple-600',
          rating: 5.0,
          reviews: 42,
          success: '100%',
          badge: 'HIGH VALUE',
          bid: '$2,450',
          preview: 'Award-winning Fintech UI designer with a specialty in mobile-first banking applications. I\'ve previously worked with 3 Series B fintech startups to overhaul their customer onboarding…',
          location: 'Dubai, UAE',
          skills: ['Mobile UI', 'Banking Apps', 'User Research', 'Figma', 'Branding'],
          bio: 'Award-winning designer passionate about building trust through great design. Formerly led design at two unicorn startups. Every pixel is intentional.',
          hourly: '$120/hr',
          completed: 29,
        },
        {
          id: 3,
          name: 'David Chen',
          initials: 'DC',
          color: 'from-emerald-400 to-green-600',
          rating: 4.8,
          reviews: 215,
          success: '95%',
          badge: null,
          bid: '$1,800',
          preview: 'I specialize in creating pixel-perfect Design Systems that scale. For your Fintech App, I propose building a modular component library that will reduce your dev time by 40%…',
          location: 'San Francisco, USA',
          skills: ['Design Systems', 'Figma', 'Storybook', 'UI Architecture', 'React'],
          bio: 'Systems thinker and UI craftsman. I build scalable component libraries that designers and engineers both love. 215 successful projects and counting.',
          hourly: '$85/hr',
          completed: 215,
        },
        {
          id: 4,
          name: 'Elena Rodriguez',
          initials: 'ER',
          color: 'from-rose-400 to-pink-600',
          rating: 4.9,
          reviews: 89,
          success: '96%',
          badge: null,
          bid: '$950',
          preview: 'Passionate about user psychology and clean aesthetics. I can help you create an app experience that not only looks professional but converts visitors into loyal users…',
          location: 'Barcelona, Spain',
          skills: ['UX Research', 'Interaction Design', 'Usability Testing', 'Figma', 'Adobe XD'],
          bio: 'UX architect who marries psychology with design. I obsess over user journeys and micro-interactions that feel effortless. Top-rated on SkillBridge for 3 years running.',
          hourly: '$75/hr',
          completed: 89,
        },
      ],
      brand: [
        {
          id: 5,
          name: 'Priya Sharma',
          initials: 'PS',
          color: 'from-amber-400 to-orange-500',
          rating: 4.9,
          reviews: 63,
          success: '97%',
          badge: 'TOP RATED',
          bid: '$2,800',
          preview: 'Brand identity is my craft. I\'ve built visual systems for over 60 e-commerce brands, with a focus on scalable design language that works across digital and print…',
          location: 'London, UK',
          skills: ['Branding', 'Logo Design', 'Style Guides', 'Illustrator', 'Typography'],
          bio: 'Brand strategist and visual identity designer. I create cohesive design systems that turn products into brands people remember.',
          hourly: '$110/hr',
          completed: 63,
        },
        {
          id: 6,
          name: 'Lucas Ferreira',
          initials: 'LF',
          color: 'from-cyan-400 to-sky-600',
          rating: 4.7,
          reviews: 38,
          success: '92%',
          badge: null,
          bid: '$1,600',
          preview: 'Specialized in e-commerce brand storytelling. My style guide deliverables include full token systems and usage documentation for dev handoff…',
          location: 'São Paulo, Brazil',
          skills: ['Brand Design', 'E-commerce', 'Style Guides', 'Figma', 'Motion'],
          bio: 'Visual storyteller who bridges brand and UX. I bring brands to life across every touchpoint — from logo to loading animation.',
          hourly: '$70/hr',
          completed: 38,
        },
      ],
      react: [
        {
          id: 7,
          name: 'Marcus Chen',
          initials: 'MC',
          color: 'from-slate-500 to-slate-700',
          rating: 5.0,
          reviews: 54,
          success: '100%',
          badge: 'HIGH VALUE',
          bid: '$4,200',
          preview: 'Full-stack React Native specialist with 6 years shipping production apps. I\'ll deliver clean, performant, and testable feature code with full documentation…',
          location: 'Toronto, Canada',
          skills: ['React Native', 'TypeScript', 'Redux', 'Node.js', 'CI/CD'],
          bio: 'Senior React Native engineer who ships fast and documents everything. Worked with teams at Series A through IPO stages. Code quality is non-negotiable.',
          hourly: '$130/hr',
          completed: 54,
        },
        {
          id: 8,
          name: 'Amara Osei',
          initials: 'AO',
          color: 'from-teal-400 to-emerald-600',
          rating: 4.8,
          reviews: 97,
          success: '94%',
          badge: null,
          bid: '$3,100',
          preview: 'React Native developer with a strong background in performance optimization and offline-first architecture. I\'ll get your feature shipped on time and on spec…',
          location: 'Accra, Ghana',
          skills: ['React Native', 'GraphQL', 'Firebase', 'Performance', 'Testing'],
          bio: 'Mobile engineer focused on developer experience and app performance. I care about bundle size, render counts, and test coverage — things that matter long term.',
          hourly: '$95/hr',
          completed: 97,
        },
      ],
    };